config/routes.rb
Rails.application.routes.draw do

  get 'about', to: 'pages#about'

  root 'articles#index'
  
  resources :articles

end

app/models/article.rb
class Article < ActiveRecord::Base
  has_unique_slug
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def index
    @articles = Article.all.order("created_at DESC")
  end

  def show
    @article = Article.find_by_slug(params[:id])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/articles/index.html.erb
<div class="col-sm-12" id="stories">  
  <div class="page-header text-muted divider">
    Articles
  </div>
</div>

<% @articles.each do |article| %>                      
<div class="row">    
  <div class="col-sm-12">
    <h3><%= article.title %></h3>
    <p><%= truncate(article.content, length: 160) %></p>
    <h4><small class="text-muted"><%= time_ago_in_words(article.created_at) %> •  <%= link_to 'read more', article_path(article) %></small></h4>
  </div>
</div>


<div class="row divider">   
  <div class="col-sm-12"><hr></div>
</div>
<% end %>

app/views/articles/show.html.erb
<div class="col-sm-12" id="stories">  
  <div class="page-header text-muted divider">
    <%= @article.title %>
  </div>
</div>
                        
<div class="row">    
  <div class="col-sm-10">
    <h4><small class="text-muted">1 hour ago</small></h4>
    <p><%= @article.content %></p>
  </div>
</div>


<div class="row divider">   
  <div class="col-sm-12"><hr></div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>BasisBlog</title>
  <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="wrapper">
  <div class="box">
    <div class="row">
      
      <div class="column col-sm-3" id="sidebar">
        <%= link_to "B", root_path, class: "logo" %>
        <ul class="nav">
          <li><%= link_to "Articles", articles_path %></li>
          <li><%= link_to "About", about_path %></li>
        </ul>
        <ul class="nav hidden-xs" id="sidebar-footer">
          <li><a href="http://www.bootply.com">Built with Ruby on Rails</a></li>
          <li><a href="http://www.bootply.com">Template by Bootply</a></li>
        </ul>
      </div>
          
      <div class="column col-sm-9" id="main">
        <div class="padding">
          <div class="full col-sm-9">
            
            <%= yield %>
            
            <div class="col-sm-12">
              <div class="page-header text-muted divider">
                Connect with Me
              </div>
            </div>
            <div class="row">
              <div class="col-sm-6">
                <%= link_to "Bitbucket", 'https://bitbucket.org/talibguyani' %> 
                <small class="text-muted">|</small> 
                <%= link_to "Coinbase", 'https://coinbase.com/talib' %>  
                <small class="text-muted">|</small> 
                <%= link_to "email", 'mailto:talib@abumaryam.com' %>  
              </div>
            </div>
            <hr>
            <div class="row" id="footer">    
              <div class="col-sm-6">
              </div>
              <div class="col-sm-6">
                <p class="pull-right"><%= link_to "Talib Guyani", 'http://abumaryam.com' %></p>
              </div>
            </div>
            <hr>
          </div>
        </div>
      </div>          
    
    </div>
  </div>
</div>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
</body>
</html>

app/views/pages/about.html.erb
<div class="col-sm-12" id="stories">  
  <div class="page-header text-muted divider">
    About
  </div>
</div>


<div class="row">    
  <div class="col-sm-12">
    <p>This Blog has been built to demostrate some of the things I can do with ruby on rails. I am hosting this site on Heroku and you can check out the source code on <%= link_to 'bitbucket', 'https://bitbucket.org/talibguyani/basisblog' %></p>
  </div>
</div>